FROM mysql:latest

# Variables de entorno para configurar la conexión a la base de datos en la nube
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=nsn4zf2b3s84x33z
ENV MYSQL_USER=y48p0dvki4no2cot
ENV MYSQL_PASSWORD=p42vms6itygss5jf
ENV MYSQL_HOST=jtb9ia3h1pgevwb1.cbetxkdyhwsb.us-east-1.rds.amazonaws.com

# Copiar archivos SQL (si es necesario) al contenedor
# COPY dump.sql /docker-entrypoint-initdb.d/

EXPOSE 3306