@apiProducts = http://localhost:4000/products
@apiCategory = http://localhost:4000/category

GET {{apiProducts}}
###
GET {{apiProducts}}/1
###
POST {{apiProducts}}
Content-Type: application/json

{
    "title": "camisa hombre",
    "descripcion": "xxxxx",
    "price": "125000",
    "category_id": 2
}

###

DELETE {{apiProducts}}/11

###

GET {{apiCategory}}
###


DELETE {{apiCategory}}/12

###

GET {{apiCategory}}/1
###
POST {{apiCategory}}
Content-Type: application/json

{
  
    "title": "MALETAS NEGRAS",
    "descripcion": "malestas NEGRAS"
}

###